"""Focused regression tests for the chain-only XSP CandidateBuilder."""

from __future__ import annotations

import copy
from datetime import datetime, timedelta, timezone

import pytest

from data_engine.quant_engine import DataQuality, QuantMetrics
from orchestrator.boundaries import DefaultTradingMandate
from orchestrator.candidate_builder import XSPCandidateBuilder, _bid_ask_mid, _xsp_symbol
from orchestrator.state import CyclePhase, CycleState


AS_OF = datetime(2026, 9, 1, 14, 30, tzinfo=timezone.utc)
EXPIRY = datetime(2026, 9, 4, tzinfo=timezone.utc)
EXPIRY_STRING = "2026-09-04"
ACCOUNT_CONTEXT = {
    "buying_power": 100_000.0,
    "equity": 100_000.0,
    "current_exposure_pct": 0.10,
    "daily_realized_pnl_pct": -0.01,
    "week_realized_pnl_pct": -0.02,
    "open_positions": 1,
    "consecutive_rejections": 0,
}
# These are the supplied fixture symbols, not symbols generated by the builder.
OCC_SYMBOLS = {
    ("put", 560.0): "XSP260904P00560000",
    ("put", 555.0): "XSP260904P00555000",
    ("put", 550.0): "XSP260904P00550000",
    ("call", 580.0): "XSP260904C00580000",
    ("call", 585.0): "XSP260904C00585000",
    ("call", 590.0): "XSP260904C00590000",
}


def metrics(iv_rank: float = 65.0, iv_percentile: float = 65.0) -> QuantMetrics:
    return QuantMetrics(
        hv30=0.15,
        hv30_quality=DataQuality.PRIMARY,
        iv_rank=iv_rank,
        iv_rank_quality=DataQuality.PRIMARY,
        iv_percentile=iv_percentile,
        iv_percentile_quality=DataQuality.PRIMARY,
        em_pct=1.5,
        em_method="iv_approximation",
        em_quality=DataQuality.PRIMARY,
        skew_25_delta=0.05,
        skew_quality=DataQuality.PRIMARY,
        momentum_zscore_20d=0.2,
        momentum_quality=DataQuality.PRIMARY,
        iv_high_regime=iv_rank >= 60 and iv_percentile >= 60,
        hv_vs_iv_ratio=0.85,
    )


def contract(
    *,
    option_type: str,
    strike: float,
    bid: float,
    ask: float,
    delta: float,
) -> dict:
    return {
        "symbol": OCC_SYMBOLS[(option_type, strike)],
        "strike": strike,
        "expiration": EXPIRY_STRING,
        "option_type": option_type,
        "underlying_symbol": "XSP",
        "source": "alpaca_options_chain",
        "observation_timestamp": AS_OF.isoformat(),
        "bid": bid,
        "ask": ask,
        "delta": delta,
    }


def recorded_chain(
    *,
    quantity: int = 1,
    put_width: float = 5.0,
    call_width: float = 5.0,
    short_put_quote: tuple[float, float] = (1.20, 1.30),
    short_call_quote: tuple[float, float] = (1.10, 1.20),
) -> dict:
    long_put_strike = 560.0 - put_width
    long_call_strike = 580.0 + call_width
    return {
        "source": "alpaca_options_chain",
        "snapshot_id": "recorded-xsp-chain-20260901-1430",
        "data_tier": "indicative",
        "snapshot_timestamp": AS_OF.isoformat(),
        "underlying_symbol": "XSP",
        "quantity": quantity,
        "put_wing_width": put_width,
        "call_wing_width": call_width,
        "expirations": [EXPIRY_STRING],
        "contracts": {
            EXPIRY_STRING: {
                "put": {
                    "560.0": contract(
                        option_type="put", strike=560.0, bid=short_put_quote[0],
                        ask=short_put_quote[1], delta=-0.16,
                    ),
                    f"{long_put_strike:.1f}": contract(
                        option_type="put", strike=long_put_strike, bid=0.30,
                        ask=0.40, delta=-0.08,
                    ),
                },
                "call": {
                    "580.0": contract(
                        option_type="call", strike=580.0, bid=short_call_quote[0],
                        ask=short_call_quote[1], delta=0.16,
                    ),
                    f"{long_call_strike:.1f}": contract(
                        option_type="call", strike=long_call_strike, bid=0.20,
                        ask=0.30, delta=0.08,
                    ),
                },
            }
        },
    }


def state_for(
    options_chain: dict | None = None,
    *,
    symbol: str = "XSP",
    dte: int = 3,
    quant_metrics: QuantMetrics | None = None,
    include_account_context: bool = True,
) -> CycleState:
    evidence = {
        "symbol": symbol,
        "spot_price": 570.0,
        "iv_atm": 0.18,
        "dte": dte,
        "options_chain": recorded_chain() if options_chain is None else options_chain,
    }
    if include_account_context:
        evidence["account_context"] = copy.deepcopy(ACCOUNT_CONTEXT)
    return CycleState(
        alpaca_account_id="test-account",
        cycle_id="test-cycle-001",
        evidence=evidence,
        quant_metrics=metrics() if quant_metrics is None else quant_metrics,
        phase=CyclePhase.QUANT,
    )


def builder(*, now: datetime = AS_OF + timedelta(minutes=1)) -> XSPCandidateBuilder:
    return XSPCandidateBuilder(clock=lambda: now)


def candidate_for(options_chain: dict | None = None, **state_kwargs):
    candidates = builder().build(
        state=state_for(options_chain, **state_kwargs), mandate=DefaultTradingMandate()
    )
    assert len(candidates) == 1
    return candidates[0]


class TestHelpers:
    def test_xsp_symbol_is_only_a_validator_for_supplied_symbol_format(self):
        assert _xsp_symbol(EXPIRY, 560.0, "put") == "XSP260904P00560000"
        assert _xsp_symbol(EXPIRY, 580.0, "call") == "XSP260904C00580000"

    def test_bid_ask_mid_rejects_missing_nonfinite_and_inverted_quotes(self):
        assert _bid_ask_mid(1.00, 1.02) == (1.00, 1.02, 1.01)
        assert _bid_ask_mid(None, 1.02) is None
        assert _bid_ask_mid(float("nan"), 1.02) is None
        assert _bid_ask_mid(1.02, 1.02) is None
        assert _bid_ask_mid(1.03, 1.02) is None


class TestChainOnlyExecutableFlow:
    def test_builds_only_from_a_fresh_validated_chain_snapshot(self):
        candidate = candidate_for()
        proposal = candidate.proposal
        assert proposal.spread.dte == 3
        assert {leg.expiration for leg in proposal.spread.legs} == {EXPIRY}
        assert proposal.spread.side.value == "iron_condor"
        assert [leg.action for leg in proposal.spread.legs] == ["SELL", "BUY", "SELL", "BUY"]

    def test_preserves_the_exact_chain_symbols_and_observed_quotes(self):
        chain = recorded_chain()
        candidate = candidate_for(chain)
        supplied = {
            raw["symbol"]
            for option_type in ("put", "call")
            for raw in chain["contracts"][EXPIRY_STRING][option_type].values()
        }
        assert {leg.symbol for leg in candidate.proposal.spread.legs} == supplied
        for leg in candidate.proposal.spread.legs:
            assert leg.mid_price == pytest.approx((leg.bid_price + leg.ask_price) / 2.0)

    def test_selects_otm_target_delta_shorts_and_existing_outer_wings(self):
        candidate = candidate_for()
        legs = candidate.proposal.spread.legs
        short_put = next(leg for leg in legs if leg.action == "SELL" and leg.option_type == "put")
        long_put = next(leg for leg in legs if leg.action == "BUY" and leg.option_type == "put")
        short_call = next(leg for leg in legs if leg.action == "SELL" and leg.option_type == "call")
        long_call = next(leg for leg in legs if leg.action == "BUY" and leg.option_type == "call")
        assert long_put.strike < short_put.strike < 570.0 < short_call.strike < long_call.strike

    def test_provenance_uses_the_chain_snapshot_without_substitution(self):
        candidate = candidate_for()
        provenance = candidate.provenance
        assert provenance.source == "alpaca_options_chain"
        assert provenance.data_tier == "indicative"
        assert provenance.underlying_symbol == "XSP"
        assert provenance.snapshot_timestamp == AS_OF
        assert provenance.contract_snapshot_id == "recorded-xsp-chain-20260901-1430"

    def test_builder_is_deterministic_for_the_same_snapshot(self):
        first = candidate_for()
        second = candidate_for()
        assert first.model_dump() == second.model_dump()

    def test_valid_chain_does_not_require_unused_contract_iv(self):
        assert candidate_for().proposal.spread.legs

    def test_valid_bs_inputs_without_a_chain_cannot_create_an_executable_candidate(self):
        state = state_for({})
        assert builder().build(state=state, mandate=DefaultTradingMandate()) == []
        assert not hasattr(XSPCandidateBuilder, "_build_from_bs")


class TestCandidateArithmetic:
    @pytest.mark.parametrize(
        ("quantity", "put_width", "call_width", "short_put_quote", "short_call_quote"),
        [
            (1, 5.0, 5.0, (1.20, 1.30), (1.10, 1.20)),
            (3, 5.0, 10.0, (1.50, 1.60), (0.90, 1.10)),
        ],
    )
    def test_net_credit_and_max_loss_use_actual_quotes_width_and_contract_count(
        self, quantity, put_width, call_width, short_put_quote, short_call_quote
    ):
        candidate = candidate_for(
            recorded_chain(
                quantity=quantity,
                put_width=put_width,
                call_width=call_width,
                short_put_quote=short_put_quote,
                short_call_quote=short_call_quote,
            )
        )
        spread = candidate.proposal.spread
        net_credit = sum(
            leg.mid_price if leg.action == "SELL" else -leg.mid_price
            for leg in spread.legs
        )
        put_legs = [leg for leg in spread.legs if leg.option_type == "put"]
        call_legs = [leg for leg in spread.legs if leg.option_type == "call"]
        put_width_from_legs = abs(put_legs[0].strike - put_legs[1].strike)
        call_width_from_legs = abs(call_legs[0].strike - call_legs[1].strike)
        assert spread.net_credit == pytest.approx(net_credit)
        assert spread.max_loss == pytest.approx(
            (max(put_width_from_legs, call_width_from_legs) - net_credit) * 100 * quantity
        )
        assert candidate.proposal.new_trade_exposure_pct == pytest.approx(
            spread.max_loss / ACCOUNT_CONTEXT["buying_power"]
        )


class TestSafeRejections:
    def test_rejects_missing_or_malformed_chain_symbols(self):
        for symbol in (None, "not-an-occ-symbol", "XSP260904P00559500"):
            chain = recorded_chain()
            chain["contracts"][EXPIRY_STRING]["put"]["560.0"]["symbol"] = symbol
            assert builder().build(state=state_for(chain), mandate=DefaultTradingMandate()) == []

    def test_rejects_missing_required_outer_wing(self):
        chain = recorded_chain()
        del chain["contracts"][EXPIRY_STRING]["call"]["585.0"]
        assert builder().build(state=state_for(chain), mandate=DefaultTradingMandate()) == []

    @pytest.mark.parametrize(
        ("field", "value"),
        [
            ("strike", None),
            ("delta", None),
            ("bid", float("inf")),
            ("ask", 1.20),
            ("mid", 99.0),
            ("option_type", "call"),
            ("expiration", "2026-09-05"),
        ],
    )
    def test_rejects_invalid_required_contract_data(self, field, value):
        chain = recorded_chain()
        chain["contracts"][EXPIRY_STRING]["put"]["560.0"][field] = value
        assert builder().build(state=state_for(chain), mandate=DefaultTradingMandate()) == []

    def test_rejects_stale_or_mismatched_observations(self):
        stale_builder = builder(now=AS_OF + timedelta(minutes=6))
        assert stale_builder.build(state=state_for(), mandate=DefaultTradingMandate()) == []
        chain = recorded_chain()
        chain["contracts"][EXPIRY_STRING]["put"]["560.0"]["observation_timestamp"] = (
            AS_OF + timedelta(seconds=1)
        ).isoformat()
        assert builder().build(state=state_for(chain), mandate=DefaultTradingMandate()) == []

    def test_rejects_invalid_chain_metadata_and_dte(self):
        for field, value in (("source", "other"), ("data_tier", "estimated"), ("quantity", 0)):
            chain = recorded_chain()
            chain[field] = value
            assert builder().build(state=state_for(chain), mandate=DefaultTradingMandate()) == []
        assert builder().build(state=state_for(recorded_chain(), dte=2), mandate=DefaultTradingMandate()) == []

    def test_rejects_missing_actual_account_context(self):
        assert builder().build(
            state=state_for(recorded_chain(), include_account_context=False),
            mandate=DefaultTradingMandate(),
        ) == []

    def test_rejects_non_xsp_and_unmet_iv_regime(self):
        assert builder().build(state=state_for(symbol="SPY"), mandate=DefaultTradingMandate()) == []
        assert builder().build(
            state=state_for(quant_metrics=metrics(iv_rank=59.9)), mandate=DefaultTradingMandate()
        ) == []

    def test_fabricated_market_data_cannot_reach_a_candidate_or_risk_gate(self):
        chain = recorded_chain()
        chain["contracts"][EXPIRY_STRING]["call"]["580.0"]["symbol"] = "XSP_STUB_CALL"
        candidates = builder().build(state=state_for(chain), mandate=DefaultTradingMandate())
        assert candidates == []
