"""
orchestrator/state.py — CycleState: the strongly-typed state schema for the LangGraph.

PRD §5.4 / RUNBOOK §12:
  - Every state field is account-scoped via alpaca_account_id.
  - thread_id = f"{alpaca_account_id}:{cycle_id}" (enforced at the checkpointer
    level, not inside state itself).
  - Bounded chief ↔ validator repair loop via repair_hop counter.
  - No credentials, API keys, or passwords in state.
"""

from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Annotated, Literal

from pydantic import BaseModel, Field, model_validator

# Runtime imports for Pydantic get_type_hints() resolution.
# data_engine.quant_engine and agents.risk_manager have no circular deps
# with orchestrator.state, so this is safe.
from data_engine.quant_engine import EvidenceEnvelope, QuantMetrics
from agents.risk_manager import RiskDecision, TradeProposal

SCHEMA_VERSION = "2.6.0"
MAX_REPAIR_HOPS = 3  # Bounded repair loop — hard limit, not LLM-controlled


def _merge_provider_usage(
    existing: dict[str, str], incoming: dict[str, str]
) -> dict[str, str]:
    """Merge independent parallel-agent telemetry without shared mutation."""
    return {**existing, **incoming}


def _merge_failure_text(existing: str, incoming: str) -> str:
    """Retain all simultaneous branch failures instead of overwriting one."""
    if not existing:
        return incoming
    if not incoming or incoming in existing:
        return existing
    return f"{existing}; {incoming}"


class CyclePhase(str, Enum):
    """The current phase/step of the cycle — used for telemetry and crash recovery."""

    PENDING = "pending"
    PRECHECK = "precheck"
    EVIDENCE = "evidence"
    QUANT = "quant"
    CANDIDATES = "candidates"
    MEMORY = "memory"
    VOLATILITY = "volatility"
    MACRO = "macro"
    TECHNICAL = "technical"
    BULL = "bull"
    BEAR = "bear"
    CHIEF = "chief"
    VALIDATOR = "validator"
    RISK_GATE = "risk_gate"
    PERSIST = "persist"
    COMPLETE = "complete"
    FAILED = "failed"


def _merge_phase(existing: CyclePhase, incoming: CyclePhase) -> CyclePhase:
    """Fail closed when parallel branches report different terminal phases."""
    if existing == CyclePhase.FAILED or incoming == CyclePhase.FAILED:
        return CyclePhase.FAILED
    return incoming


class CandidateReadiness(str, Enum):
    """Whether the candidate boundary supplied executable market contracts."""

    READY = "ready"
    NOT_READY = "not_ready"


# ---------------------------------------------------------------------------
# Agent result models (simplified — cross-plane contracts)
# ---------------------------------------------------------------------------


class VolatilityReport(BaseModel):
    """Output of the Volatility Analyst node."""

    regime: Literal["high_iv", "low_iv", "neutral", "unknown"] = "unknown"
    confidence: float = Field(ge=0.0, le=1.0, description="Confidence 0–1")
    rationale: str = ""
    iv_regime_signal: str = ""
    provider: str = ""

    def to_dict(self) -> dict:
        return self.model_dump()


class MacroReport(BaseModel):
    """Output of the Macro/News Analyst node."""

    sentiment: Literal["bullish", "bearish", "neutral", "uncertain"] = "uncertain"
    confidence: float = Field(ge=0.0, le=1.0)
    key_events: list[str] = Field(default_factory=list)
    circuit_breaker_active: bool = False
    circuit_breaker_reason: str = ""
    provider: str = ""

    def to_dict(self) -> dict:
        return self.model_dump()


class TechnicalReport(BaseModel):
    """Output of the Technical Manager node."""

    trend: Literal["bullish", "bearish", "neutral"] = "neutral"
    momentum_score: float = Field(ge=-3.0, le=3.0, description="Z-score scaled")
    directional_conviction: float = Field(ge=0.0, le=1.0)
    summary: str = ""
    provider: str = ""

    def to_dict(self) -> dict:
        return self.model_dump()


class BullBearReport(BaseModel):
    """Output of Bull or Bear Research agent."""

    verdict: Literal["proceed", "reject", "modify"] = "reject"
    score: float = Field(ge=0.0, le=1.0, description="Conviction 0–1")
    arguments: list[str] = Field(default_factory=list)
    risk_flags: list[str] = Field(default_factory=list)
    provider: str = ""

    def to_dict(self) -> dict:
        return self.model_dump()


class ChiefReport(BaseModel):
    """Chief's qualitative selection of a CandidateBuilder proposal.

    Contract selection, prices, DTE, sizing, and risk values remain locked in
    ``ValidatedCandidate.proposal`` and are never generated by the Chief.
    """

    model_config = {"extra": "forbid"}

    proposal_id: str
    side: Literal["iron_condor", "bull_put_spread", "bear_call_spread", "skip"] = "skip"
    rationale: str = ""
    confidence: float = Field(ge=0.0, le=1.0)
    provider: str = ""

    def to_dict(self) -> dict:
        return self.model_dump()


class ValidatorReport(BaseModel):
    """Output of the proposal validator."""

    valid: bool = False
    errors: list[str] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)
    suggested_fix: str = ""

    def to_dict(self) -> dict:
        return self.model_dump()


class CandidateProvenance(BaseModel):
    """Provenance required before a candidate may be evaluated by RiskManager."""

    model_config = {"extra": "forbid"}

    source: Literal["alpaca_options_chain"]
    data_tier: Literal["indicative", "opra"]
    underlying_symbol: str = Field(min_length=1)
    snapshot_timestamp: datetime
    contract_snapshot_id: str = Field(min_length=1)


class ValidatedCandidate(BaseModel):
    """A deterministic, options-chain-backed proposal supplied by CandidateBuilder.

    The Chief may select this object by ``proposal_id`` but never supplies or
    modifies its contracts, prices, account context, or risk values.
    """

    model_config = {"extra": "forbid"}

    proposal: "TradeProposal"
    provenance: CandidateProvenance

    @property
    def proposal_id(self) -> str:
        return self.proposal.proposal_id


# ---------------------------------------------------------------------------
# CycleState — the LangGraph state schema
# ---------------------------------------------------------------------------


class CycleState(BaseModel):
    """
    Strongly-typed state for the AeroQuant LangGraph.

    Field design principles:
      - Only fields that change during the graph traversal are mutable (no defaults
        for required fields — they must be set by the appropriate node).
      - No credentials, API keys, or passwords.
      - repair_hop is the bounded repair-loop counter (PRD §5.4).
      - phase tracks the current step for crash recovery.
    """

    model_config = {"extra": "forbid"}

    # ---- Identity ----
    alpaca_account_id: str = Field(
        min_length=1,
        description="Alpaca account ID — used for thread_id and all persistence",
    )
    cycle_id: str = Field(
        min_length=1,
        description="Unique cycle ID (UUID or timestamp-based)",
    )

    # ---- Phase tracking ----
    phase: Annotated[CyclePhase, _merge_phase] = Field(default=CyclePhase.PENDING)
    started_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )
    completed_at: datetime | None = None

    # ---- Precheck ----
    precheck_passed: bool = False
    precheck_reason: str = ""

    # ---- Evidence / Data ----
    evidence: dict = Field(
        default_factory=dict,
        description="Raw market data snapshot (spot, IV, chain, news)"
    )

    # ---- Quant Engine output ----
    quant_metrics: "QuantMetrics | None" = Field(
        default=None,
        description="All §5.1 deterministic metrics from QuantEngine"
    )
    evidence_envelope: "EvidenceEnvelope | None" = None

    # ---- Candidate generation ----
    candidate_readiness: CandidateReadiness = CandidateReadiness.NOT_READY
    candidate_reason: str = "CandidateBuilder has not supplied a validated candidate"
    candidates: list[ValidatedCandidate] = Field(
        default_factory=list,
        description="Validated options-chain candidates from CandidateBuilder",
    )
    risk_proposal: "TradeProposal | None" = Field(
        default=None,
        description=(
            "Typed deterministic candidate selected by Chief. CandidateBuilder, not "
            "an LLM node, supplies contracts, prices, and account-risk context."
        ),
    )

    # ---- Memory context (per-cycle working memory) ----
    memory_context: dict = Field(
        default_factory=dict,
        description="Working memory: episodic retrieval, semantic rules, recent cycles"
    )

    # ---- LLM branch outputs ----
    volatility_report: "VolatilityReport | None" = None
    macro_report: "MacroReport | None" = None
    technical_report: "TechnicalReport | None" = None
    bull_report: "BullBearReport | None" = None
    bear_report: "BullBearReport | None" = None
    chief_report: "ChiefReport | None" = None
    validator_report: "ValidatorReport | None" = None

    # ---- Chief selection (the report is qualitative; risk_proposal is immutable data-plane input) ----
    selected_candidate_id: str | None = None
    candidate_selection_error: str = ""

    # ---- Risk Gate ----
    risk_decision: "RiskDecision | None" = None

    # ---- Persistence ----
    persisted: bool = False
    persist_error: str = ""

    # ---- Repair loop ----
    repair_hop: int = Field(
        default=0,
        ge=0,
        le=MAX_REPAIR_HOPS,
        description=f"Bounded repair hop counter. Max {MAX_REPAIR_HOPS}. "
                    "Chief ↔ Validator loop only."
    )

    # ---- Error / failure state ----
    error: Annotated[str, _merge_failure_text] = Field(
        default="",
        description="Human-readable error message if phase == FAILED"
    )
    failed_node: Annotated[str, _merge_failure_text] = Field(
        default="",
        description="Which node raised the error"
    )

    # ---- Telemetry ----
    provider_used: Annotated[dict[str, str], _merge_provider_usage] = Field(
        default_factory=dict,
        description="Which provider served each LLM call: {node: provider_name}"
    )

    @model_validator(mode="after")
    def _reject_secrets_in_untyped_context(self) -> "CycleState":
        """Keep raw evidence/memory containers from becoming credential stores."""
        prohibited = {
            "api_key",
            "api_secret",
            "password",
            "credentials",
            "provider_credentials",
            "access_token",
            "refresh_token",
        }

        def inspect(value: object) -> None:
            if isinstance(value, dict):
                for key, nested in value.items():
                    if str(key).lower() in prohibited:
                        raise ValueError("CycleState must not contain credentials or secrets")
                    inspect(nested)
            elif isinstance(value, list):
                for nested in value:
                    inspect(nested)

        inspect(self.evidence)
        inspect(self.memory_context)
        return self

    def to_thread_id(self) -> str:
        """
        Account-scoped thread_id per PRD §5.4.

        Must be used as the checkpointer thread_id — never cycle_id alone.
        """
        return f"{self.alpaca_account_id}:{self.cycle_id}"

    def next_phase(self, next_phase: CyclePhase) -> "CycleState":
        """Return a copy with the phase updated (immutable update pattern)."""
        return self.model_copy(deep=True, update={"phase": next_phase})

    def advance_repair_hop(self) -> "CycleState":
        """Return a copy with repair_hop incremented."""
        if self.repair_hop >= MAX_REPAIR_HOPS:
            return self.model_copy(deep=True)
        return self.model_copy(
            deep=True,
            update={"repair_hop": self.repair_hop + 1}
        )

    @property
    def at_max_repair_hops(self) -> bool:
        return self.repair_hop >= MAX_REPAIR_HOPS

    def is_failure(self) -> bool:
        return self.phase == CyclePhase.FAILED or bool(self.error)
